const OTP_PURPOSES = Object.freeze({
  REGISTER: "REGISTER",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CHANGE_EMAIL: "CHANGE_EMAIL",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  ENABLE_2FA: "ENABLE_2FA",
  DISABLE_2FA: "DISABLE_2FA",
});

const OTP_EXPIRY_MINUTES = 10;
const OTP_MAX_ATTEMPTS = 5;

const getOtpExpiryDate = () =>
  new Date(Date.now() + OTP_EXPIRY_MINUTES * 60 * 1000);

module.exports = {
  OTP_PURPOSES,
  OTP_EXPIRY_MINUTES,
  OTP_MAX_ATTEMPTS,
  getOtpExpiryDate,
};
